slam_toolbox:
  ros__parameters:
    use_sim_time: false

    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: /scan_match
    resolution: 0.025
    max_laser_range: 5.0

    minimum_time_interval: 0.3
    transform_publish_period: 0.02
    map_update_interval: 1.0

    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.04
    minimum_travel_heading: 0.04
    scan_buffer_size: 20

    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
